[tool.poetry]
name = "online-store"
version = "0.1.0"
description = ""
authors = ["Nika Alexandrovna <megrelynika@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.6"
psycopg2-binary = "^2.9.10"
python-dotenv = "^1.1.1"
pillow = "^11.3.0"
psycopg2 = "^2.9.10"
poetry-core = "^2.2.1"
ipython = "^9.6.0"
black = "^25.9.0"
django-countries = "^7.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
