# Generated by Django 5.2.6 on 2025-10-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
    ]
